name: copy_gh_pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Checkout github repo
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Push to github repo
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        
        git pull origin gh-pages

        wget -O index.html https://raw.githubusercontent.com/nuuuwan/pdf_txt_mp3/main/data/index.html

        git add .
        git commit -m "copy_gh_pages $(date)"
        git push origin gh-pages

      
