name: pipeline

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 * * * *'

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install build

    - name: Checkout github repo
      uses: actions/checkout@v2
      with:
        ref: 'main'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Run pipeline
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python workflows/pipeline.py
        python workflows/build_gh_pages.py

    - name: Push to github repo
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        
        git add .
        git commit -m "pipeline $(date)"
        git push origin main

      
